config/routes.rb
Wedding::Application.routes.draw do
  get "home/index"

  resources :users do
    resources :rsvps
  end

  root :to => 'home#index'

  resources :user_sessions
  resources :password_resets
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'info' => 'home#info'  

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :rsvps

  attr_readonly   :username
  attr_accessible :email, :password, :password_confirmation, :rsvps
  authenticates_with_sorcery!

  validates_length_of :password, :minimum => 4, :message => "must be at least 4 characters long", :if => :password
  validates_confirmation_of :password, :message => "should match confirmation", :if => :password

  validates :username, :uniqueness => true
  validates :email, :format => { :with => /^.+\@.+$/, :message => "must be a valid" }, :if => "!email.nil? and email.length > 0"

  def is_admin?
    id == 1
  end

  def fullname
    i = rsvps.length

    if (rsvps.reduce false do |haskids,rsvp| haskids ||= rsvp.is_child? end) && !rsvps[0].is_child? then
      rsvps[0].name + " and Family"
    else
      rsvps.map do |rsvp| { :index => i-=1, :name => rsvp.name } end.
        reduce "" do |fullname,rsvp|
          fullname += if rsvp[:name].nil? then "Guest" else rsvp[:name] end + 
                      case rsvp[:index] when 0 then "" when 1 then " and " else ", " end
        end
    end
  end

  def state
    if !is_valid_email? then
      :update_email
    elsif !has_confirmed? then
      :confirm_rsvp
    else
      :wait_for_menu
    end
  end

  def next_action
    case state
      when :update_email then "Please provide your e-mail address so that we can keep you informed"
      when :confirm_rsvp then "Please complete the RSVP sections below"
      when :wait_for_menu then "See \"Further Information\" above"
      else ""
    end
  end

  def is_valid_email?
    if !self[:email].nil? && self[:email].match( /^.+\@.+$/ ) then true else false end     # want to return a boolean
  end

  def has_confirmed?
    rsvps.reduce true do |state,rsvp| state &&= rsvp.attending != "Unsure" end
  end

  def generate_username
    r = rand 10000
    a = ((r + 3103) % 26 + 97).chr
    "%s%04d" % [a,r]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

# uncomment this line if admin gets deleted
#  skip_before_filter :require_login, :only => [:new, :create, :activate]

  # GET /users
  # GET /users.json
  def index
    @users = if current_user.is_admin? then User.all else [current_user] end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = if current_user.is_admin? then User.find(params[:id]) else current_user end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = if current_user.is_admin? then User.find(params[:id]) else current_user end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = if current_user.is_admin? then User.find(params[:id]) else current_user end

    # if password field isn't filled in, default to previous password
    if params[:user][:password].nil? || params[:user][:password] == ""
      params[:user][:password] = @user.password
      params[:user][:password_confirmation] = @user.password
    end

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = if current_user.is_admin? then User.find(params[:id]) else current_user end
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="edit_form">
  <div class="field">
   <%= f.label :username, "Invitation code" %>
   <% if @user.new_record? then %>
     <%= f.text_field :username %>
   <% else %>
     <div class="vanilla_text"><%= @user.username %></div>
   <% end %>
  </div>
  <div class="field">
   <%= f.label :email, "E-mail address" %>
    <%= f.text_field :email %>
  </div>
  <br/><br/>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm password" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <br/><br/>

  <div class="action">
    <%= f.submit "Update Details" %>
  </div>
</div>
<br />
<% end %>

app/views/users/edit.html.erb
<h1>Update contact details and login information</h1>

<%= render 'form' %>

<%= link_to 'Back', @user %>

app/views/users/index.html.erb
<h1>All Invitations</h1>
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>
<table>
  <tr>
    <th>Invitation</th>
    <th>Last Login</th>
    <th>Confirmed?</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.fullname %></td>
    <td><%= user.last_login_at %></td>
    <td><% if user.has_confirmed? %><b style="color:green">Y</b><% end %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to_if current_user_is_admin?, 'New User', new_user_path do nil end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="invitation_outline">
<div class="invitation">
Miss Shonagh Buchan Dodd <br />
and <br />
Mr Christopher Edward West <br />
request the pleasure of the company of <br />
<span class="invitation_emphasis"><%= @user.fullname %></span> <br />
at their marriage <br />
at the Royal Chace Hotel, Enfield, EN2 8AR <br />
on the 31st of March, 2012 <br />
at 4pm <br />
Reception to follow
</div>
</div>
<h2 style="text-align: center"><%= @user.next_action %></h2>
<div class="hr"></div>
<%= link_to image_tag( (@user.is_valid_email? && "Yes" || "No") + ".png", :alt => @user.next_action, :class => "attending" ), edit_user_path(@user) %>

<div class="rsvp">
<div class="rotext">Invitation code: <%= @user.username %> </div>
<div class="rotext">E-mail address: <%= @user.email %> </div>

<br/>
<%= link_to 'Change these details', edit_user_path(@user) %>
</div>

<div class="hr"></div>

<%= render @user.rsvps %>

<%= link_to 'Add Child(ren) to Invitation', new_user_rsvp_path(@user) %>


<br/><br/><br/><br/>