config/routes.rb
Wedding::Application.routes.draw do
  get "home/index"

  resources :users do
    resources :rsvps
  end

  root :to => 'home#index'

  resources :user_sessions
  resources :password_resets
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'info' => 'home#info'  

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, :except => [:destroy]
  
  def new
    @user = User.new
  end
  
  def create
    respond_to do |format|

      if !params[:username].empty? then
        auto_login( User.where( :username => params[:username] ).first || false, params[:remember] )
        @user = @current_user
      else
        @user = login(params[:email],params[:password],params[:remember])
      end

      if @user then
        format.html { redirect_to( @user, :notice => 'Login successful.') }
        format.xml { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { flash.now[:alert] = "Login failed."; render :action => "new" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    logout
    redirect_to(:users, :notice => 'Logged out!')
  end

end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_forgot_password_form.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
  </div>
  <div class="actions">
    <%= submit_tag "Reset my password!" %>
  </div>
<% end %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>

  <div class="left_hand_box">
  Please enter your personal code here:
  <div class="narrow_field">
    <%= label_tag :username, "Code" %>
    <%= text_field_tag :username %>
  </div>
  <br/>
  <div class="action">
    <%= submit_tag "Login with Code" %>
  </div>

  </div>

  <div class="right_hand_box">
  Or you can log in with your e-mail address and password:
  <div class="narrow_field">
    <%= label_tag "E-mail" %>
    <%= text_field_tag :email %>
  </div>
  <div class="narrow_field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
  <br/>
  <div class="action">
    <%= submit_tag "Login with E-mail" %>
  </div>
  <div class="narrow_field">
   <%= label_tag "keep me logged in" %>
    <%= check_box_tag :remember %>
  </div>
  </div>

<br clear="all" />
<div class="hr"></div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>
<%= render 'form' %>

<h1>Forgot Password?</h1>
<%= render 'forgot_password_form' %>